export const EsperTierData = [
  {
    esperName: "Abigail",
    deity: "Frigga",
    role: "Defender",
    type: "Inferno",
    stars: "5",
    mythImg: "../Images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "../Images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Abigail_avatar-2.png",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 10,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Ahmed",
    deity: "Geb",
    role: "Support",
    type: "Wind",
    stars: "4",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Ahmed_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Ashley",
    deity: "Heimdall",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Ashley_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 7,
    hero_column_shdwgale: 7,
    hero_column_shdwstream: 7,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 8,
  },

  {
    esperName: "Biondina",
    deity: "Poseidon",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Biondina_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 0,
    hero_column_story: 8,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 8,
    hero_column_shdwfire: 6,
    hero_column_shdwgale: 6,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 9,
    hero_column_tt: 7,
    hero_column_pw: 6,
  },

  {
    esperName: "Brewster",
    deity: "Garmr",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Brewster_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 0,
    hero_column_story: 9,
    hero_column_kronos: 8,
    hero_column_apep: 9,
    hero_column_fafnir: 5,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 7,
    hero_column_tt: 9,
    hero_column_pw: 7,
  },

  {
    esperName: "Camille",
    deity: "Hati",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Camille_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Cang Ji",
    deity: "Cang Jie",
    role: "Support",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Cang_Ji_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Cecilia",
    deity: "Isis",
    role: "Support",
    type: "Shimmer",
    stars: "5",
    charImg: "images/Character/AaHeadShots/square/Cecilia_avatar.webp",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Cecilia_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 6.4,
    hero_column_story: 8,
    hero_column_kronos: 7,
    hero_column_apep: 6,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 5,
    hero_column_shdwgale: 5,
    hero_column_shdwstream: 5,
    hero_column_sonicmir: 6,
    hero_column_tt: 7,
    hero_column_pw: 9,
  },
  {
    esperName: "Clara",
    deity: "Hera",
    role: "Support",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Clara_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.7,
    hero_column_story: 10,
    hero_column_kronos: 8,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 7,
    hero_column_shdwgale: 9,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 10,
  },
  {
    esperName: "Donar",
    deity: "Thor",
    role: "Defender",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Donar_avatar_new.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 6.6,
    hero_column_story: 9,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 5,
    hero_column_shdwgale: 5,
    hero_column_shdwstream: 5,
    hero_column_sonicmir: 9,
    hero_column_tt: 8,
    hero_column_pw: 7,
  },

  {
    esperName: "Elaine",
    deity: "Nyx",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Elaine_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Embla",
    deity: "Ymir",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Embla_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.0,
    hero_column_story: 6,
    hero_column_kronos: 6,
    hero_column_apep: 10,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 6,
    hero_column_shdwgale: 6,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 10,
    hero_column_tt: 9,
    hero_column_pw: 8,
    hero_column_IT: 9,
    hero_column_Cube: 9,
    hero_column_sentinal: 9,
    hero_column_CI: 9,
  },
  {
    esperName: "Elliot",
    deity: "Thoth",
    role: "Controller",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Elliot_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 6.8,
    hero_column_story: 8,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 6,
    hero_column_shdwgale: 6,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 7,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },

  {
    esperName: "Everett",
    deity: "Tyr",
    role: "Fighter",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Everett_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 7.6,
    hero_column_story: 9,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 7,
    hero_column_shdwgale: 7,
    hero_column_shdwstream: 7,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 10,
  },
  {
    esperName: "Fatum Sisters",
    deity: "Normir",
    role: "Support",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Fatum_Sisters_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 6.9,
    hero_column_story: 9,
    hero_column_kronos: 7,
    hero_column_apep: 7,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 6,
    hero_column_shdwgale: 6,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 8,
    hero_column_tt: 7,
    hero_column_pw: 7,
  },
  {
    esperName: "Feng Nuxi",
    deity: "Nuwa",
    role: "Support",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Feng_Nuxi_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 8.8,
    hero_column_story: 10,
    hero_column_kronos: 8,
    hero_column_apep: 8,
    hero_column_fafnir: 8,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 10,
    hero_column_tt: 10,
    hero_column_pw: 10,
  },
  {
    esperName: "Gabrielle",
    deity: "Njord",
    role: "Support",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Gabrielle_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.7,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 7,
    hero_column_fafnir: 10,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 10,
    hero_column_pw: 10,
  },
  {
    esperName: "Gaius",
    deity: "Zeus",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Gaius_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 8.8,
    hero_column_story: 10,
    hero_column_kronos: 10,
    hero_column_apep: 7,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 10,
    hero_column_shdwgale: 7,
    hero_column_shdwstream: 7,
    hero_column_sonicmir: 10,
    hero_column_tt: 10,
    hero_column_pw: 10,
  },
  {
    esperName: "Hyde",
    deity: "Hades",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Hyde_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 7.3,
    hero_column_story: 7,
    hero_column_kronos: 6,
    hero_column_apep: 6,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 7,
    hero_column_shdwgale: 7,
    hero_column_shdwstream: 7,
    hero_column_sonicmir: 8,
    hero_column_tt: 9,
    hero_column_pw: 10,
  },

  {
    esperName: "Ife",
    deity: "Meretseger",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Ife_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 7.1,
    hero_column_story: 8,
    hero_column_kronos: 7,
    hero_column_apep: 8,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 6,
    hero_column_shdwgale: 6,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 7,
    hero_column_tt: 9,
    hero_column_pw: 7,
  },

  {
    esperName: "Intisar",
    deity: "Kauket",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Intisar_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 8,
    hero_column_story: 10,
    hero_column_kronos: 10,
    hero_column_apep: 7,
    hero_column_fafnir: 6,
    hero_column_shdwfire: 9,
    hero_column_shdwgale: 7,
    hero_column_shdwstream: 6,
    hero_column_sonicmir: 9,
    hero_column_tt: 8,
    hero_column_pw: 8,
  },
  {
    esperName: "Jiang Jiuli",
    deity: "Chiyou",
    role: "Fighter",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Jiang_Jiuli_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Jin Yuyao",
    deity: "Queen Mother",
    role: "Support",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Jin_Yuyao_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },

  {
    esperName: "Leora",
    deity: "Athena",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Leora_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },

  {
    esperName: "Lewis",
    deity: "Ares",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Lewis_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Li Ling",
    deity: "Nezha",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Li_Ling_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Lucas",
    deity: "Apollo",
    role: "Controller",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Lucas_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },

  {
    esperName: "Narmer",
    deity: "Ra",
    role: "Fighter",
    type: "Inferno",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Narmer_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Inferno.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Ollie",
    deity: "Osiris",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Ollie_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Ophelia",
    deity: "Thanatos",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/ShadowDecreeIcon.webp",
    affilName: "Shadow Decree",
    charImg: "../Images/Character/AaHeadShots/square/Ophelia_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Raven",
    deity: "Odin",
    role: "Fighter",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Raven_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Sally",
    deity: "Sif",
    role: "Support",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Sally_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },

  {
    esperName: "Sienna",
    deity: "Gaia",
    role: "Support",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Greek_avatar.webp",
    mythName: "Greek",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Sienna_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Tang Xuan",
    deity: "Sun Wukong",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Tang_Xuan_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Tevor",
    deity: "Sphinx",
    role: "Fighter",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Tevor_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Tiye",
    deity: "Nut",
    role: "Controller",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Tiye_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Triki",
    deity: "Loki",
    role: "Controller",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Norse_avatar.webp",
    mythName: "Norse",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Triki_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Unas",
    deity: "Shu",
    role: "Support",
    type: "Shimmer",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Unas_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Shimmer.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Yun Chuan",
    deity: "Yang Jian",
    role: "Fighter",
    type: "Wind",
    stars: "5",
    mythImg: "images/Misc/Chinese_avatar.webp",
    mythName: "Chinese",
    affilImg: "images/Misc/EsperUnionIcon.webp",
    affilName: "Esper Union",
    charImg: "../Images/Character/AaHeadShots/square/Yun_Chuan_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Wind.png",
    hero_column_overall: 8.5,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
  {
    esperName: "Zora",
    deity: "Amunet",
    role: "Fighter",
    type: "Flow",
    stars: "5",
    mythImg: "images/Misc/Egyptian_avatar.webp",
    mythName: "Egyptian",
    affilImg: "images/Misc/WandererIcon.webp",
    affilName: "Wanderer",
    charImg: "../Images/Character/AaHeadShots/square/Zora_avatar.webp",
    typeImg: "../Images/Misc/Stars_TypeIcons/Flow.png",
    hero_column_overall: 0,
    hero_column_story: 10,
    hero_column_kronos: 7,
    hero_column_apep: 10,
    hero_column_fafnir: 7,
    hero_column_shdwfire: 8,
    hero_column_shdwgale: 8,
    hero_column_shdwstream: 8,
    hero_column_sonicmir: 9,
    hero_column_tt: 9,
    hero_column_pw: 9,
  },
];

function avg() {
  let list = EsperTierData;
  list.forEach(function (item) {
    let sum =
      item.hero_column_story +
      item.hero_column_kronos +
      item.hero_column_apep +
      item.hero_column_fafnir +
      item.hero_column_shdwfire +
      item.hero_column_shdwgale +
      item.hero_column_shdwstream +
      item.hero_column_sonicmir +
      item.hero_column_tt +
      item.hero_column_pw;
    let overallAvg = (sum / 10).toFixed(1);
    item.hero_column_overall = overallAvg;
  });
}

avg();
